# Generated by Django 4.2.7 on 2025-12-09 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expiration', models.BigIntegerField()),
            ],
            options={
                'db_table': 'cache',
            },
        ),
        migrations.CreateModel(
            name='FailedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'failed_jobs',
            },
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_1', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_1_desa', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_1_kota', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_2', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_2_desa', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat_2_kota', models.CharField(blank=True, max_length=255, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=50, null=True)),
                ('pendapatan_per_bulan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identitas',
            },
        ),
        migrations.CreateModel(
            name='JobBatch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_jobs', models.IntegerField()),
                ('pending_jobs', models.IntegerField()),
                ('failed_jobs', models.IntegerField()),
                ('failed_job_ids', models.TextField()),
                ('options', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('finished_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_batches',
            },
        ),
        migrations.CreateModel(
            name='Kuesioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kuesioner',
            },
        ),
        migrations.CreateModel(
            name='KuesionerPertanyaan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pertanyaan', models.TextField(blank=True, null=True)),
                ('tipe', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('textarea', 'Textarea')], max_length=50, null=True)),
                ('wajib_diisi', models.BooleanField(default=False)),
                ('urutan', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('kuesioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan', to='valemis.kuesioner')),
            ],
            options={
                'db_table': 'kuesioner_pertanyaan',
            },
        ),
        migrations.CreateModel(
            name='KuesionerRespondenAsetBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persil_id', models.BigIntegerField()),
                ('jenis_bangunan', models.CharField(blank=True, max_length=100, null=True)),
                ('luas_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('permanen', models.BooleanField(null=True)),
                ('bangunan_utama', models.CharField(blank=True, max_length=50, null=True)),
                ('material_utama', models.CharField(blank=True, max_length=100, null=True)),
                ('sanitasi', models.BooleanField(null=True)),
                ('listrik', models.BooleanField(null=True)),
                ('suplai_air', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kuesioner_responden_aset_bangunan',
                'indexes': [models.Index(fields=['persil_id'], name='kues_aset_persil_idx')],
            },
        ),
        migrations.CreateModel(
            name='KuesionerResponden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('identitas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respon_kuesioner', to='valemis.identitas')),
            ],
            options={
                'db_table': 'kuesioner_responden',
            },
        ),
        migrations.CreateModel(
            name='KuesionerPertanyaanOpsi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opsi_teks', models.CharField(blank=True, max_length=255, null=True)),
                ('opsi_nilai', models.CharField(blank=True, max_length=100, null=True)),
                ('urutan', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi', to='valemis.kuesionerpertanyaan')),
            ],
            options={
                'db_table': 'kuesioner_pertanyaan_opsi',
            },
        ),
        migrations.CreateModel(
            name='KuesionerPertanyaanGrup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('urutan', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('kuesioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup_pertanyaan', to='valemis.kuesioner')),
            ],
            options={
                'db_table': 'kuesioner_pertanyaan_grup',
            },
        ),
        migrations.AddField(
            model_name='kuesionerpertanyaan',
            name='pertanyaan_grup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pertanyaan', to='valemis.kuesionerpertanyaangrup'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField()),
                ('reserved_at', models.BigIntegerField(blank=True, null=True)),
                ('available_at', models.BigIntegerField()),
                ('created_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['queue'], name='jobs_queue_index')],
            },
        ),
    ]
