# Generated by Django 4.2.7 on 2025-12-09 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonClaim',
            fields=[
                ('polygon_claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('geom_wkt', models.TextField()),
                ('type_poligon', models.TextField()),
                ('sumber_data', models.TextField()),
            ],
            options={
                'verbose_name': 'Polygon Claim',
                'verbose_name_plural': 'Polygon Claims',
                'db_table': 'tbl_Polygon_claim',
            },
        ),
    ]
