# Generated by Django 4.2.7 on 2025-12-09 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0002_polygonclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bukti',
            fields=[
                ('id_bukti', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.TextField()),
                ('object_id', models.IntegerField()),
                ('kategori', models.TextField()),
                ('deskripsi', models.TextField()),
                ('file_ref', models.TextField()),
            ],
            options={
                'verbose_name': 'Bukti',
                'verbose_name_plural': 'Bukti',
                'db_table': 'tbl_bukti',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id_claim', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateField()),
                ('jenis_claim', models.TextField()),
                ('uraian', models.TextField()),
                ('status', models.TextField()),
                ('kanal', models.TextField()),
                ('sumber', models.TextField()),
                ('dokumen_klaim', models.TextField()),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'tbl_claim',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.TextField()),
                ('object_id', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('aktor', models.TextField()),
                ('aksi', models.TextField()),
                ('catatan', models.TextField()),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'tbl_log',
            },
        ),
        migrations.CreateModel(
            name='Mediasi',
            fields=[
                ('id_mediasi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('mediator', models.TextField()),
                ('lokasi', models.TextField()),
                ('hasil', models.TextField()),
                ('ringkasan', models.TextField()),
                ('dokumen', models.TextField()),
                ('id_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.claim')),
            ],
            options={
                'verbose_name': 'Mediasi',
                'verbose_name_plural': 'Mediasi',
                'db_table': 'tbl_mediasi',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id_parcel', models.AutoField(primary_key=True, serialize=False)),
                ('nama_parcel', models.TextField()),
                ('desa', models.TextField()),
                ('kecamatan', models.TextField()),
                ('kabupaten', models.TextField()),
                ('provinsi', models.TextField()),
                ('status_penguasaan', models.TextField()),
                ('nomor_sertifikat', models.TextField()),
                ('pemegang_hak', models.TextField()),
                ('area_ha', models.FloatField()),
                ('srid', models.IntegerField()),
                ('sumber_data', models.TextField()),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'db_table': 'tbl_parcel',
            },
        ),
        migrations.CreateModel(
            name='PenggunaanLahan',
            fields=[
                ('id_reclaim_act', models.AutoField(primary_key=True, serialize=False)),
                ('id_reclaim_area', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('aktivitas', models.TextField()),
                ('luas_ha', models.FloatField()),
                ('area', models.TextField()),
                ('survival_rate_pct', models.FloatField()),
                ('dokumen', models.TextField()),
                ('sub_spasial', models.TextField()),
            ],
            options={
                'verbose_name': 'Penggunaan Lahan',
                'verbose_name_plural': 'Penggunaan Lahan',
                'db_table': 'tbl_Penggunaan Lahan',
            },
        ),
        migrations.CreateModel(
            name='PerkaraTimeline',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('case_type', models.TextField()),
                ('id_case', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('stage', models.TextField()),
                ('catatan', models.TextField()),
                ('dokumen', models.TextField()),
            ],
            options={
                'verbose_name': 'Perkara Timeline',
                'verbose_name_plural': 'Perkara Timeline',
                'db_table': 'tbl_perkara_timeline',
            },
        ),
        migrations.CreateModel(
            name='Putusan',
            fields=[
                ('id_putusan', models.AutoField(primary_key=True, serialize=False)),
                ('case_type', models.TextField()),
                ('id_case', models.IntegerField()),
                ('tingkat', models.TextField()),
                ('nomor_putusan', models.TextField()),
                ('tanggal_putus', models.DateField()),
                ('hasil', models.TextField()),
                ('ringkasan', models.TextField()),
                ('tautan_putusan', models.TextField()),
            ],
            options={
                'verbose_name': 'Putusan',
                'verbose_name_plural': 'Putusan',
                'db_table': 'tbl_putusan',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('sh_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('tipe', models.TextField()),
                ('kategori', models.TextField()),
                ('alamat', models.TextField()),
                ('kontak', models.TextField()),
                ('srid', models.IntegerField()),
                ('geom_wkt', models.TextField()),
                ('interest_1_5_incase', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('influence_1_5_incase', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'db_table': 'tbl_stakeholder',
            },
        ),
        migrations.AlterField(
            model_name='polygonclaim',
            name='geom_wkt',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='StatusLahan',
            fields=[
                ('pid_lahan', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.TextField()),
                ('status_lahan', models.TextField()),
                ('tgl_inven', models.DateField()),
                ('tgl_bebas', models.DateField(blank=True, null=True)),
                ('penggunaan_ops', models.TextField()),
                ('bln_thn_penggunaan', models.TextField()),
                ('keterangan', models.TextField()),
                ('poligon_sub_spasial', models.TextField()),
                ('id_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.parcel')),
            ],
            options={
                'verbose_name': 'Status Lahan',
                'verbose_name_plural': 'Status Lahan',
                'db_table': 'tbl_Status Lahan',
            },
        ),
        migrations.CreateModel(
            name='StakeholderInvolvement',
            fields=[
                ('id_involvement', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.TextField()),
                ('object_id', models.IntegerField()),
                ('peran', models.TextField()),
                ('sejak', models.DateField()),
                ('hingga', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField()),
                ('sh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.stakeholder')),
            ],
            options={
                'verbose_name': 'Stakeholder Involvement',
                'verbose_name_plural': 'Stakeholder Involvements',
                'db_table': 'tbl_stakeholder_involvement',
            },
        ),
        migrations.CreateModel(
            name='Pidana',
            fields=[
                ('id_pidana', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_lp', models.TextField()),
                ('pasal_diduga', models.TextField()),
                ('instansi', models.TextField()),
                ('status', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField(blank=True, null=True)),
                ('ringkasan', models.TextField()),
                ('id_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.claim')),
            ],
            options={
                'verbose_name': 'Pidana',
                'verbose_name_plural': 'Pidana',
                'db_table': 'tbl_pidana',
            },
        ),
        migrations.CreateModel(
            name='Perdata',
            fields=[
                ('id_perdata', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_perkara', models.TextField()),
                ('tingkat', models.TextField()),
                ('pengadilan', models.TextField()),
                ('status', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_putus', models.DateField(blank=True, null=True)),
                ('pokok_perkara', models.TextField()),
                ('nilai_ganti_rugi', models.FloatField()),
                ('id_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.claim')),
            ],
            options={
                'verbose_name': 'Perdata',
                'verbose_name_plural': 'Perdata',
                'db_table': 'tbl_perdata',
            },
        ),
        migrations.AddField(
            model_name='parcel',
            name='polygon_claim',
            field=models.ForeignKey(db_column='Polygon_CLaim_ID', on_delete=django.db.models.deletion.CASCADE, to='valemis.polygonclaim'),
        ),
        migrations.CreateModel(
            name='MediasiSesi',
            fields=[
                ('id_sesi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('agenda', models.TextField()),
                ('hasil', models.TextField()),
                ('notulen', models.TextField()),
                ('id_mediasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.mediasi')),
            ],
            options={
                'verbose_name': 'Mediasi Sesi',
                'verbose_name_plural': 'Mediasi Sesi',
                'db_table': 'tbl_mediasi_sesi',
            },
        ),
        migrations.CreateModel(
            name='Komplain',
            fields=[
                ('id_komplain', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('ringkas', models.TextField()),
                ('detail', models.TextField()),
                ('kategori', models.TextField()),
                ('kanal_penerimaan', models.TextField()),
                ('tingkat_dampak_1_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('prioritas_1_5', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.TextField()),
                ('dokumen', models.TextField()),
                ('id_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.parcel')),
                ('id_pelapor_stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.stakeholder')),
            ],
            options={
                'verbose_name': 'Komplain',
                'verbose_name_plural': 'Komplain',
                'db_table': 'tbl_komplain',
            },
        ),
        migrations.CreateModel(
            name='ClaimRiwayat',
            fields=[
                ('id_claim_hist', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('status', models.TextField()),
                ('deskripsi', models.TextField()),
                ('petugas', models.TextField()),
                ('dokumen', models.TextField()),
                ('id_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.claim')),
            ],
            options={
                'verbose_name': 'Claim Riwayat',
                'verbose_name_plural': 'Claim Riwayat',
                'db_table': 'tbl_claim_riwayat',
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='id_parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valemis.parcel'),
        ),
    ]
