# Generated by Django 4.2.7 on 2025-12-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0005_censusquestion_censussurvey_censusmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinventory',
            name='agama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='alasan_berhenti',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='alasan_hutang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='asal_etnis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='bahasa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='bekerja_12_bulan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='bisa_membaca_menulis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='defisit_pangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='disabilitas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='hubungan_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='hutang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='identifikasi_dampak',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_proyek',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='karakteristik_khusus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kecukupan_pangan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kepemilikan_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='keterampilan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kondisi_kesehatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pekerjaan_utama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pelayanan_listrik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pembagian_kerja',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pengeluaran_bulanan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='penghasilan_tahunan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='penyakit_umum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='rekening_bank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sanitasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sedang_sekolah',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='status_perkawinan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sumber_air',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='surveyed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tabungan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tempat_asal_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tempat_pelayanan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tipe_rumah',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
