# Generated by Django 4.2.7 on 2025-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0006_assetinventory_agama_assetinventory_alasan_berhenti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='status',
            field=models.CharField(choices=[('Negosiasi Tahap 1', 'Negosiasi Tahap 1'), ('Negosiasi Tahap 2', 'Negosiasi Tahap 2'), ('Negosiasi Tahap 3', 'Negosiasi Tahap 3'), ('Putusan Clear', 'Putusan Clear'), ('Putusan Pengadilan', 'Putusan Pengadilan')], default='Negosiasi Tahap 1', max_length=50),
        ),
    ]
