# Generated by Django 4.2.7 on 2025-12-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0007_alter_litigation_status'),
    ]

    operations = [
        # Q2: ID Rumah Tangga
        migrations.AddField(
            model_name='assetinventory',
            name='id_rumah_tangga',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Rumah Tangga'),
        ),
        # "Lainnya" fields for dropdowns with custom input
        migrations.AddField(
            model_name='assetinventory',
            name='agama_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Agama Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='asal_etnis_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asal Etnis Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='bahasa_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bahasa Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tempat_asal_kk_tentukan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Asal KK (Tentukan)'),
        ),
        # Q29: Berapa banyak orang yang tinggal di rumah tangga
        migrations.AddField(
            model_name='assetinventory',
            name='jumlah_orang_rumah_tangga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Orang dalam Rumah Tangga'),
        ),
        # Q36: Usia
        migrations.AddField(
            model_name='assetinventory',
            name='usia',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usia'),
        ),
        # Q45-54: Pekerjaan detail fields
        migrations.AddField(
            model_name='assetinventory',
            name='pekerjaan_utama_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan Utama Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_pekerjaan_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi Pekerjaan Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jumlah_bulan_bekerja',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Bulan Bekerja dalam Setahun'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='penghasilan_per_bulan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Penghasilan per Bulan'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pekerjaan_sekunder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan Sekunder'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pekerjaan_sekunder_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pekerjaan Sekunder Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_pekerjaan_sekunder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi Pekerjaan Sekunder'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_pekerjaan_sekunder_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi Pekerjaan Sekunder Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jumlah_bulan_bekerja_sekunder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Bulan Bekerja Sekunder'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='penghasilan_sekunder_per_bulan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Penghasilan Sekunder per Bulan'),
        ),
        # Q62: Keterampilan (already exists as "keterampilan")
        migrations.AddField(
            model_name='assetinventory',
            name='keterampilan_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keterampilan Lainnya'),
        ),
        # Q64: Penyakit umum (already exists)
        # Q68: Defisit pangan cara menutupi
        migrations.AddField(
            model_name='assetinventory',
            name='defisit_pangan_lainnya',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Defisit Pangan Lainnya'),
        ),
        # Q74: Jenis tabungan detail
        migrations.AddField(
            model_name='assetinventory',
            name='tabungan_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabungan Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='hutang_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hutang Lainnya'),
        ),
        # Q80-84: Dampak pembebasan lahan
        migrations.AddField(
            model_name='assetinventory',
            name='pernah_dampak_proyek',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pernah Dampak Proyek Lain'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_proyek_lain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Proyek Lain'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='luas_lahan_dibebaskan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Luas Lahan Dibebaskan (m2)'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pernah_pengungsi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pernah Menjadi Pengungsi'),
        ),
        # Q85-95: Bisnis detail fields
        migrations.AddField(
            model_name='assetinventory',
            name='punya_bisnis',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Punya Bisnis'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='lokasi_bisnis_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi Bisnis Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kepemilikan_bisnis_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kepemilikan Bisnis Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sejak_kapan_bisnis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sejak Kapan Bisnis Aktif'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_bisnis_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Bisnis Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jumlah_pegawai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pegawai'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pendapatan_rata_bisnis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Pendapatan Rata-rata Bisnis'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='deskripsi_produk_layanan',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Produk dan Layanan'),
        ),
        # Housing detail fields
        migrations.AddField(
            model_name='assetinventory',
            name='tipe_rumah_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipe Rumah Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='pelayanan_listrik_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pelayanan Listrik Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sumber_air_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sumber Air Lainnya'),
        ),
        # Q102-103: Kerentanan dan Komunikasi
        migrations.AddField(
            model_name='assetinventory',
            name='karakteristik_krt',
            field=models.TextField(blank=True, null=True, verbose_name='Karakteristik Kepala Rumah Tangga'),
        ),
    ]
