# Generated by Django 4.2.7 on 2025-12-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0008_add_missing_census_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumah_tangga_no', models.CharField(blank=True, max_length=50, null=True)),
                ('id_aset', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_type', models.CharField(choices=[('Tanah', 'Tanah'), ('Tanaman', 'Tanaman'), ('Pohon', 'Pohon'), ('Bangunan', 'Bangunan'), ('Sumber Daya Alam', 'Sumber Daya Alam')], max_length=50)),
                ('jenis_tanah', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Tanah')),
                ('terdaftar_di', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terdaftar Di')),
                ('luas_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Luas (m2)')),
                ('status_pemilik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Pemilik')),
                ('pemilik_sebelumnya', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pemilik Sebelumnya')),
                ('tenurial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tenurial (Y/T)')),
                ('catatan_tanah', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('jenis_tanaman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Tanaman')),
                ('usia_tanaman', models.IntegerField(blank=True, null=True, verbose_name='Usia Tanaman')),
                ('kondisi_tanaman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kondisi Tanaman')),
                ('sumber_air_tanaman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sumber Air')),
                ('gambar_tanaman', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar')),
                ('jenis_pohon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Pohon')),
                ('jumlah_pohon', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pohon')),
                ('luas_pohon', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Luas Pohon')),
                ('produktif', models.CharField(blank=True, max_length=10, null=True, verbose_name='Produktif (Y/T)')),
                ('dewasa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dewasa (Y/T)')),
                ('produksi_per_tahun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produksi per Tahun')),
                ('kondisi_pohon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kondisi Pohon')),
                ('gambar1_pohon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 1')),
                ('gambar2_pohon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 2')),
                ('gambar3_pohon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 3')),
                ('jenis_bangunan', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Bangunan')),
                ('luas_bangunan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Luas Bangunan')),
                ('permanen_sementara', models.CharField(blank=True, max_length=50, null=True, verbose_name='Permanen/Sementara')),
                ('primer_sekunder', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer/Sekunder')),
                ('bahan_utama', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bahan Utama')),
                ('sanitarian', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sanitarian')),
                ('pasokan_listrik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pasokan Listrik')),
                ('persediaan_air', models.CharField(blank=True, max_length=100, null=True, verbose_name='Persediaan Air')),
                ('gambar1_bangunan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 1')),
                ('gambar2_bangunan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 2')),
                ('gambar3_bangunan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 3')),
                ('gambar4_bangunan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gambar 4')),
                ('jenis_sumber_daya_alam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Sumber Daya Alam')),
                ('produktivitas_per_tahun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produktivitas per Tahun')),
                ('luas_sda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Luas SDA (m2)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_details', to='valemis.assetinventory')),
            ],
            options={
                'verbose_name': 'Asset Inventory Detail',
                'verbose_name_plural': 'Asset Inventory Details',
                'db_table': 'asset_inventory_detail',
                'ordering': ['asset_type', 'id'],
            },
        ),
    ]
