# Generated by Django 4.2.7 on 2025-12-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0009_add_asset_inventory_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetinventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asset Inventory (Kuisioner)', 'verbose_name_plural': 'Asset Inventories (Kuisioner)'},
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='alasan_berhenti',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='building_area',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='certificate_status',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='code',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='hubungan_responden',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='identifikasi_dampak',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='jenis_proyek_lain',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='karakteristik_krt',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='kondisi_kesehatan',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='pembagian_kerja',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='tanggal_survei',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='tempat_asal_kk_tentukan',
        ),
        migrations.RemoveField(
            model_name='assetinventory',
            name='village',
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='alasan_hutang_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alasan Hutang Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='alasan_penghentian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='38. Alasan Penghentian'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='alasan_penghentian_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alasan Penghentian Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='anggota_nama_belakang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='29. Nama Belakang (Anggota)'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='anggota_nama_depan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='28. Nama Depan (Anggota)'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='desa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='15. Desa'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='disabilitas_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disabilitas Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='hubungan_responden_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='20. Hubungan Responden dengan KK'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='hutang_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='65. Hutang Detail'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='id_dampak',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='27. ID Dampak'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='jenis_proyek_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Proyek Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kesehatan_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kesehatan Lainnya'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='kondisi_kesehatan_kronis',
            field=models.TextField(blank=True, null=True, verbose_name='40. Kondisi Kesehatan Kronis'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='koordinat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='6. Koordinat'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='metode_komunikasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='89. Metode Komunikasi'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='no_anggota',
            field=models.IntegerField(blank=True, null=True, verbose_name='No.'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='sumber_informasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='88. Sumber Informasi'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tabungan_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='64. Tabungan Detail'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tanggal',
            field=models.DateField(blank=True, null=True, verbose_name='3. Tanggal'),
        ),
        migrations.AddField(
            model_name='assetinventory',
            name='tempat_asal_tentukan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tentukan Tempat Asal'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='agama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='22. Agama'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='alasan_hutang',
            field=models.TextField(blank=True, null=True, verbose_name='66. Alasan Hutang'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='asal_etnis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='23. Asal Etnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='bahasa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='24. Bahasa'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='bekerja_12_bulan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='41. Bekerja 12 Bulan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='bisa_membaca_menulis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='34. Bisa Membaca/Menulis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='defisit_pangan',
            field=models.TextField(blank=True, null=True, verbose_name='58. Defisit Pangan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='deskripsi_produk_layanan',
            field=models.TextField(blank=True, null=True, verbose_name='78. Deskripsi Produk'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='disabilitas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='39. Disabilitas'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='hubungan_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='30. Hubungan dengan KK'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='hutang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='63. Hutang'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='id_rumah_tangga',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='2. ID Rumah Tangga'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='id_unik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='5. ID Unik (Entitas Terdampak)'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jenis_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='75. Jenis Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='31. Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jenis_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='43. Jenis Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jenis_proyek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='68. Jenis Proyek'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jumlah_bulan_bekerja',
            field=models.IntegerField(blank=True, null=True, verbose_name='45. Jumlah Bulan Bekerja'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jumlah_bulan_bekerja_sekunder',
            field=models.IntegerField(blank=True, null=True, verbose_name='49. Jumlah Bulan Sekunder'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jumlah_orang_rumah_tangga',
            field=models.IntegerField(blank=True, null=True, verbose_name='26. Jumlah Orang di Rumah Tangga'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='jumlah_pegawai',
            field=models.IntegerField(blank=True, null=True, verbose_name='76. Jumlah Pegawai'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='17. Kabupaten'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='karakteristik_khusus',
            field=models.TextField(blank=True, null=True, verbose_name='83. Karakteristik Khusus'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='16. Kecamatan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kecukupan_pangan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='57. Kecukupan Pangan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kepemilikan_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='73. Kepemilikan Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='keterampilan',
            field=models.TextField(blank=True, null=True, verbose_name='51. Keterampilan/Profesi'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kode_enumerator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='1. Kode Enumerator'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='kode_foto_survei',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='4. Kode Foto Survei'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='lokasi_bisnis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='72. Lokasi Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='lokasi_pekerjaan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='44. Lokasi Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='lokasi_pekerjaan_sekunder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='48. Lokasi Sekunder'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='lokasi_pekerjaan_sekunder_lainnya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasi Sekunder Lainnya'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='lokasi_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='36. Lokasi Sekolah'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='luas_lahan_dibebaskan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='69. Luas Lahan (m2)'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='10. Nama Ayah'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_belakang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='9. Nama Belakang'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_depan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='7. Nama Depan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_kakek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='11. Nama Kakek'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_pasangan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='12. Nama Pasangan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_responden',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='19. Nama Responden'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nama_tengah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='8. Nama Tengah'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='14. NIK'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='nomor_telepon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='13. Nomor Telepon'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pekerjaan_sekunder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='47. Pekerjaan Sekunder'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pekerjaan_utama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='42. Pekerjaan Utama'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pelayanan_listrik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='80. Pelayanan Listrik'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pendapatan_rata_bisnis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='77. Pendapatan Rata Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='37. Pendidikan Terakhir'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pengeluaran_bulanan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='60. Pengeluaran Bulanan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='penghasilan_per_bulan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='46. Penghasilan per Bulan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='penghasilan_sekunder_per_bulan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='50. Penghasilan Sekunder'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='penghasilan_tahunan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='59. Penghasilan Tahunan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='penyakit_umum',
            field=models.TextField(blank=True, null=True, verbose_name='55. Penyakit Umum'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pernah_dampak_proyek',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='67. Pernah Dampak Proyek'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='pernah_pengungsi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='70. Pernah Pengungsi'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='18. Provinsi'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='punya_bisnis',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='71. Punya Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='rekening_bank',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='61. Rekening Bank'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='sanitasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='82. Sanitasi'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='sedang_sekolah',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='35. Sedang Sekolah'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='sejak_kapan_bisnis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='74. Sejak Kapan Bisnis'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='status_perkawinan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='33. Status Perkawinan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='sumber_air',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='81. Sumber Air'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='surveyed_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Disurvei oleh'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='tabungan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='62. Tabungan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='tempat_asal_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='25. Tempat Asal KK'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='tempat_pelayanan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='56. Tempat Pelayanan'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='tipe_rumah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='79. Tipe Rumah'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui pada'),
        ),
        migrations.AlterField(
            model_name='assetinventory',
            name='usia',
            field=models.IntegerField(blank=True, null=True, verbose_name='32. Usia'),
        ),
    ]
