# Generated manually for census LARAP models

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valemis', '0011_alter_assetinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusKepalaKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asset', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('id_project', models.CharField(blank=True, max_length=50, null=True)),
                ('kode_enumerator', models.CharField(blank=True, max_length=50, null=True)),
                ('id_rumah_tangga', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('kode_foto_survei', models.CharField(blank=True, max_length=50, null=True)),
                ('entitas_terdampak', models.CharField(blank=True, max_length=100, null=True)),
                ('koordinat', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_depan', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_tengah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_belakang', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_kakek', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_pasangan', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=100, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_responden', models.CharField(blank=True, max_length=255, null=True)),
                ('hubungan_responden', models.CharField(blank=True, max_length=200, null=True)),
                ('identifikasi_dampak', models.CharField(blank=True, max_length=200, null=True)),
                ('identifikasi_dampak_lainnya', models.TextField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=200, null=True)),
                ('agama_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('asal_etnis', models.CharField(blank=True, max_length=200, null=True)),
                ('asal_etnis_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('bahasa', models.CharField(blank=True, max_length=200, null=True)),
                ('bahasa_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_asal_kk', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_asal_kk_tentukan', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_orang_rumah_tangga', models.IntegerField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('status_perkawinan', models.CharField(blank=True, max_length=200, null=True)),
                ('bisa_membaca_menulis', models.CharField(blank=True, max_length=200, null=True)),
                ('sedang_sekolah', models.CharField(blank=True, max_length=200, null=True)),
                ('sekolah_dimana', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_penghentian', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_penghentian_lainnya', models.TextField(blank=True, null=True)),
                ('disabilitas', models.CharField(blank=True, max_length=200, null=True)),
                ('disabilitas_lainnya', models.TextField(blank=True, null=True)),
                ('kondisi_kesehatan_kronis', models.CharField(blank=True, max_length=200, null=True)),
                ('kondisi_kesehatan_kronis_lainnya', models.TextField(blank=True, null=True)),
                ('bekerja_12_bulan', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_utama_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_utama_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_bulan_bekerja', models.IntegerField(blank=True, null=True)),
                ('penghasilan_per_bulan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pekerjaan_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_sekunder_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_sekunder_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_bulan_bekerja_sekunder', models.IntegerField(blank=True, null=True)),
                ('penghasilan_sekunder_per_bulan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('keterampilan', models.CharField(blank=True, max_length=200, null=True)),
                ('keterampilan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('penyakit_umum_anak', models.TextField(blank=True, null=True)),
                ('penyakit_umum_remaja', models.TextField(blank=True, null=True)),
                ('penyakit_umum_dewasa', models.TextField(blank=True, null=True)),
                ('penyakit_umum_lansia', models.TextField(blank=True, null=True)),
                ('tempat_pelayanan_kesehatan', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_pelayanan_kesehatan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('kecukupan_pangan', models.CharField(blank=True, max_length=200, null=True)),
                ('defisit_pangan_cara_menutupi', models.TextField(blank=True, null=True)),
                ('defisit_pangan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_1_pertanian', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_1_sumber', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_1_sumber_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_1_primer_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_1_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pendapatan_2_pertanian', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_2_sumber', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_2_sumber_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_2_primer_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_2_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pendapatan_3_pertanian', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_3_sumber', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_3_sumber_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_3_primer_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('pendapatan_3_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('penghasilan_tahunan_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pengeluaran_1_item', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_1_item_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_1_frekuensi', models.IntegerField(blank=True, null=True)),
                ('pengeluaran_1_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pengeluaran_2_item', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_2_item_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_2_frekuensi', models.IntegerField(blank=True, null=True)),
                ('pengeluaran_2_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pengeluaran_3_item', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_3_item_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pengeluaran_3_frekuensi', models.IntegerField(blank=True, null=True)),
                ('pengeluaran_3_jumlah', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pengeluaran_bulanan_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rekening_bank', models.CharField(blank=True, max_length=200, null=True)),
                ('punya_tabungan', models.CharField(blank=True, max_length=200, null=True)),
                ('punya_hutang', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_tabungan', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_tabungan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_hutang', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_hutang_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_hutang', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_hutang_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('pernah_terdampak_proyek', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_proyek_sebelumnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_proyek_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_lahan_dibebaskan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pernah_pengungsi', models.CharField(blank=True, max_length=200, null=True)),
                ('punya_bisnis', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_bisnis', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_bisnis_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('kepemilikan_bisnis', models.CharField(blank=True, max_length=200, null=True)),
                ('kepemilikan_bisnis_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('sejak_kapan_bisnis', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_bisnis', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_bisnis_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_pegawai', models.IntegerField(blank=True, null=True)),
                ('pendapatan_bisnis_per_bulan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('deskripsi_produk_layanan', models.TextField(blank=True, null=True)),
                ('tipe_rumah', models.CharField(blank=True, max_length=200, null=True)),
                ('tipe_rumah_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_rumah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pelayanan_listrik', models.CharField(blank=True, max_length=200, null=True)),
                ('pelayanan_listrik_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('sumber_air', models.CharField(blank=True, max_length=200, null=True)),
                ('sumber_air_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('sanitasi', models.CharField(blank=True, max_length=200, null=True)),
                ('karakteristik_kerentanan', models.TextField(blank=True, null=True)),
                ('sumber_informasi', models.CharField(blank=True, max_length=200, null=True)),
                ('metode_komunikasi', models.CharField(blank=True, max_length=200, null=True)),
                ('nib', models.CharField(blank=True, max_length=100, null=True)),
                ('letak_tanah', models.CharField(blank=True, max_length=200, null=True)),
                ('status_tanah', models.CharField(blank=True, max_length=200, null=True)),
                ('surat_bukti_tanah', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_tanah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tahun_kelola_lahan', models.IntegerField(blank=True, null=True)),
                ('asal_usul_perolehan', models.CharField(blank=True, max_length=200, null=True)),
                ('biaya_perolehan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('batas_utara', models.CharField(blank=True, max_length=200, null=True)),
                ('batas_selatan', models.CharField(blank=True, max_length=200, null=True)),
                ('batas_timur', models.CharField(blank=True, max_length=200, null=True)),
                ('batas_barat', models.CharField(blank=True, max_length=200, null=True)),
                ('hm_sarusun', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_ruang', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                # Tanaman fields (44 types)
                ('tanaman_merica', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_alpukat', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_aren', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_belimbing', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_belukar', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_bonglai', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_buah_naga', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_cabai', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_cempedak', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_cengkeh', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_cokelat', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_durian', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jahe_merah', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jambu', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jambu_air', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jambu_batu', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jambu_biji', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jati_putih', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jengkol', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jeruk', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_jeruk_nipis', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kapuk', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kecombrang', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kelapa', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kelapa_sawit', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kelor', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kopi', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kunyit', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_kunyit_hitam', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_langsat', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_lengkuas', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_mangga', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_nanas', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_nangka', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_nilam', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_pepaya', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_pinang', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_rambutan', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_serai', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_singkong', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_sirsak', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_sukun', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_talas', models.IntegerField(blank=True, default=0, null=True)),
                ('tanaman_ubi', models.IntegerField(blank=True, default=0, null=True)),
                ('benda_lain_tanah', models.TextField(blank=True, null=True)),
                ('pembebanan_hak_tanah', models.TextField(blank=True, null=True)),
                ('perkiraan_dampak', models.TextField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('fungsi_kawasan', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Census Kepala Keluarga',
                'verbose_name_plural': 'Census Kepala Keluarga',
                'db_table': 'census_kepala_keluarga',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CensusIndividu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asset', models.CharField(db_index=True, editable=False, max_length=20)),
                ('id_project', models.CharField(blank=True, max_length=50, null=True)),
                ('no_urut', models.IntegerField(blank=True, null=True)),
                ('id_rumah_tangga', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_depan', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_belakang', models.CharField(blank=True, max_length=100, null=True)),
                ('nik', models.CharField(blank=True, max_length=20, null=True)),
                ('hubungan_dengan_kk', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('status_perkawinan', models.CharField(blank=True, max_length=200, null=True)),
                ('bisa_membaca_menulis', models.CharField(blank=True, max_length=200, null=True)),
                ('sedang_sekolah', models.CharField(blank=True, max_length=200, null=True)),
                ('sekolah_dimana', models.CharField(blank=True, max_length=200, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_penghentian', models.CharField(blank=True, max_length=200, null=True)),
                ('alasan_penghentian_lainnya', models.TextField(blank=True, null=True)),
                ('disabilitas', models.CharField(blank=True, max_length=200, null=True)),
                ('disabilitas_lainnya', models.TextField(blank=True, null=True)),
                ('kondisi_kesehatan_kronis', models.CharField(blank=True, max_length=200, null=True)),
                ('kondisi_kesehatan_kronis_lainnya', models.TextField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('bekerja_12_bulan', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_utama_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_utama', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_utama_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_bulan_bekerja', models.IntegerField(blank=True, null=True)),
                ('penghasilan_per_bulan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pekerjaan_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_sekunder_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_sekunder', models.CharField(blank=True, max_length=200, null=True)),
                ('lokasi_pekerjaan_sekunder_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('jumlah_bulan_bekerja_sekunder', models.IntegerField(blank=True, null=True)),
                ('penghasilan_sekunder_per_bulan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('keterampilan', models.CharField(blank=True, max_length=200, null=True)),
                ('keterampilan_lainnya', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_keluarga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_keluarga', to='valemis.censuskepalakel uarga')),
            ],
            options={
                'verbose_name': 'Census Individu',
                'verbose_name_plural': 'Census Individu',
                'db_table': 'census_individu',
                'ordering': ['kepala_keluarga', 'no_urut'],
            },
        ),
    ]
